# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
        - breaking ⛏️
    - title: Exciting New Features 🚀
      labels:
        - Semver-Minor
        - enhancement
        - 'enhancement 🚀'
    - title: '🐞 Bug Fixes'
      labels:
        - bug 🐞
        - bugfix
    - title: Other Changes
      labels:
        - "*"
