version: '4'

services:

  docs:
    container_name: ghentcdh.app.docs
    extends:
      file: docker-compose.base.yml
      service: nx-app-base-dev
    build:
      target: node-docs
    depends_on:
      database_app:
        condition: service_healthy
        restart: true
    ports:
      - "5000:5000"
