name: "Setup"
description: "Load node cache"


runs:
  using: "composite"
  steps:
    - name: Cache node modules
      uses: actions/cache@v5
      with:
        path: node_modules
        key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v6
      with:
        version: latest
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
        scope: "@ghentcdh"
