name: Labeler


on:
    pull_request:
        branches:
            - main
            - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Run Labeler
              uses: crazy-max/ghaction-github-labeler@v4.1.0
              with:
                  skip-delete: true

            - name: Label the pr
              uses: actions/labeler@v5
