name: Labeler


on:
    pull_request:
        branches:
            - main
            - master

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run Labeler
              uses: crazy-max/ghaction-github-labeler@v4.1.0
              with:
                  skip-delete: true
                  
            - name: Label the pr
              uses: actions/labeler@v5
